#include"header.h"
#include"prototype.h"

int compress_3(int fd,char *ma,char * argv)
{
	char * temp_name;
	int cf,j=1,i,k,n=1,chek=0;
	char ch;
	unsigned char c,byt,temp1,temp2,ctemp[3],temp3;
	temp_name=(char *)malloc(24);
	strcpy(temp_name,argv);
	strcat(temp_name,"_comp");
	cf=open(temp_name,O_WRONLY|O_CREAT,0666);
	lseek(fd,0,SEEK_SET);
	byt=byt^byt;
	while(read(fd,&ch,1))
	{	
		chek=0;
		for(k=0;k<3;k++)
			ctemp[k]=ctemp[k]^ctemp[k];
		k=0;
		c=c^c;
		for(i=0;*(ma+i)!=ch;i++);
		do
		{
			sprintf(&ctemp[k],"%d",(int)i%10);
			ctemp[k]=ctemp[k]-48;
			k++;

			i=i/10;			
		}while(i);
		c=ctemp[2]*100+ctemp[1]*10+ctemp[0];
		if(!read(fd,&ch,1))
		{
			chek=1;
			lseek(fd,1,SEEK_CUR);
		}
		lseek(fd,-1,SEEK_CUR);
		if(n%3==1)
		{	
		if(j%3==1)
		{
			temp1=c;
			temp1=temp1<<5;
			byt=byt|temp1;
			if(chek)	
			{
				sprintf(&temp3,"%d",7);
				temp3=temp3-48;
				temp3=temp3<<5;
				temp3=temp3>>3;
				byt=byt|temp3;
				write(cf,&byt,1);
				break;
			}
		}
		else if(j%3==2)
		{
			temp1=c;
			temp1=temp1<<5;
			temp1=temp1>>3;
			byt=byt|temp1;
			if(chek)	
			{
				sprintf(&temp3,"%d",7);
				temp3=temp3-48;
				temp3=temp3<<5;
				temp3=temp3>>6;
				byt=byt|temp3;
				write(cf,&byt,1);
				sprintf(&temp3,"%d",7);
				temp3=temp3<<7;
				write(cf,&temp3,1);
				break;
			}
		}
		else
		{	
			temp2=c;
			temp1=c;
			temp1=temp1<<5;
			temp1=temp1>>6;
			byt=byt|temp1;
			write(cf,&byt,1);
			if(chek)	
			{
				temp2=temp2<<7;
				sprintf(&temp3,"%d",7);
				temp3=temp3-48;
				temp3=temp3<<4;
				temp3=temp2|temp3;
				write(cf,&temp3,1);
				break;
			}
			n++;
			byt=byt^byt;
		}
	j++;
	}
	else if(n%3==2)
	{
		if(j%3==1)
		{
			temp1=temp2;
			temp1=temp1<<7;
			byt=byt|temp1;
			temp1=c;
			temp1=temp1<<5;
			temp1=temp1>>1;
			byt=byt|temp1;
			if(chek)
			{
				sprintf(&temp3,"%d",7);
				temp3=temp3<<5;
				temp3=temp3>>4;
				byt=byt|temp3;
				write(cf,&byt,1);
				break;
			}
		}
		else if(j%3==2)
		{
			temp1=c;
			temp1=temp1<<5;
			temp1=temp1>>4;
			byt=byt|temp1;
			if(chek)
			{
				sprintf(&temp3,"%d",7);
				temp3=temp3-48;
				temp2=temp3;
				temp3=temp3<<5;
				temp3=temp3>>7;
				byt=byt|temp3;
				write(cf,&byt,1);
				temp2=temp2<<6;
				write(cf,&temp2,1);
				break;
			}
		}
		else
		{
			temp2=c;
			temp1=c;
			temp1=temp1<<7;
			temp1=temp1>>7;
			byt=byt|temp1;
			write(cf,&byt,1);
			if(chek)
			{
				temp2=temp2<<6;
				sprintf(&temp3,"%d",7);
				temp3=temp3-48;
				temp3=temp3<<3;
				temp2=temp2|temp3;
				write(cf,&temp2,1);
				break;
			}
			n++;
			byt=byt^byt;
		}
	j++;
	}
	else
	{
		if(j%3==1)
		{
			temp1=temp2;
			temp1=temp1<<6;
			byt=byt|temp1;
			temp1=c;
			temp1=temp1<<5;
			temp1=temp1>>2;
			byt=byt|temp1;
			if(chek)
			{
				sprintf(&temp3,"%d",7);
				temp3=temp3-48;
				temp3=temp3<<5;
				temp3=temp3>>5;
				write(cf,&temp3,1);
				break;
			}
		}
		else if(j%3==2)
		{
			temp1=c;	
			temp1=temp1<<5;
			temp1=temp1>>5;
			byt=byt|temp1;
			write(cf,&byt,1);
			n++;
			j++;
			byt=byt^byt;
		}
	j++;
	}
	}
	return 0;
}
